### ISSUE TITLE
대여관리 화면에서 헤더가 바뀌지 않는 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#100]
## 💁 설명

- 대여관리 헤더가 바뀌지 않고, 대여관리 화면 전 진입했던 화면의 헤더가 유지됨

## 🎬 시나리오
1.대여관리 화면 진입
2.
3.

## 📢 예상 결과
- 대여관리 화면 진입 시, 대여관리 화면의 헤더 노출

## 🃏 실제 결과 
- 대여관리 화면 전 진입했던 화면의 헤더가 유지됨

## 📌 스크린샷
![Screenshot_20220727-092650_Chrome.jpg](https://user-images.githubusercontent.com/110044464/181134750-b0f1faf2-a9f3-4140-a20e-ce25cadf8707.jpg)

**Comment by minjeong930610** [comment]
여기는 금주 작업이 시작된 페이지여서 쪼금만 기다려주세용
