### ISSUE TITLE
포스트보기 화면 제목 가려짐

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#101]
## 💁 설명

- 포스트보기 화면 제목 가려짐

## 🎬 시나리오
1. 홈
2. 책 클릭해 포스트 보기 화면 진입
3.

## 📢 예상 결과
- 제목이랑 지은이가 보인다.

## 🃏 실제 결과 
- 헤더랑 겹쳐져서 숨어있다. 스크롤 해서 당겨야지 보임

## 📌 스크린샷
- 가능하다면 오류메세지나 동작결과에 대해 스크린샷을 첨부해주세요

**Comment by minjeong930610** [comment]
아 layout margin 적용 클래스에 오타가 생겨있네요 공통 영역 수정하시다가 그랬나봐요 다음 배포에 수정 적용하겠습니다^^
