### ISSUE TITLE
프로필 이미지 비율에 맞게 줄이기

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#102]
## 💁 설명

- 프로필 이미지 사진을 등록하면 사진이 찌부됩니다.

## 🎬 시나리오
1. 나의 책방-프로필 편집-사진등록
2. 
3.

## 📢 예상 결과
- 사진앨범에 있는 사진과 등록한 사진이 같다.

## 🃏 실제 결과 
- 사이즈가 줄어들면서 찌부됩니다.. 같은 비율로 줄어들면 좋겠습니다

## 📌 스크린샷
- 
![IMG_3278](https://user-images.githubusercontent.com/110044546/181223310-fa0f0842-faa3-452a-94a5-d5e773623448.PNG)
![IMG_3279](https://user-images.githubusercontent.com/110044546/181223366-fae27765-a584-4c8b-bdb2-da17580620be.jpg)

**Comment by minjeong930610** [comment]
넵 비율 맞게 들어가도록 수정할게요 조금 확대되는 건 있습니다! 비율 맞게 줄여 놓고 100px에 맞게 늘려서 채우기보다는 나을 거 같아서요
