### ISSUE TITLE
위치 터치 범위 확대하기

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#103]
## 💁 설명

- 위치 변경을 하려고 할 때 터치 범위가 좁아 한 번에 페이지가 바뀌지 않습니다. 텍스트를 선택해도 전환이 일어났으면 좋겠어요.

## 🎬 시나리오
1. 홈-신내동 텍스트 터치
2.
3.

## 📢 예상 결과
- 위치변경 페이지가 뜬다.

## 🃏 실제 결과 
- 화살표를 터치해야지만 뜬다.

## 📌 스크린샷
- 
![IMG_52C08DCC5B94-1](https://user-images.githubusercontent.com/110044546/181225171-857a49fd-5bee-4954-a1ca-39701ce2ce53.jpeg)

**Comment by minjeong930610** [comment]
오케이

**Comment by makingbird** [comment]
현재 텍스트 눌러도 변경이 됩니다! 개발 완료로 생각되어 확인 완료로 상태 변경하겠습니다.

**Comment by makingbird** [comment]
아 개발 완료에서만 보는 거였죠...... 죄송...
