### ISSUE TITLE
개인책방 띄어쓰기하지 않기

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#104]
## 💁 설명

- 서비스 소개에 보이는 로고 이미지처럼 개인책방 단어 붙여서 쓰기(통일)
- 탭과, 바탕화면에서

## 🎬 시나리오
1.
2.
3.

## 📢 예상 결과
- 개인책방

## 🃏 실제 결과 
- 개인 책방 -> 개인책방

## 📌 스크린샷

<img width="188" alt="스크린샷 2022-07-27 오후 10 09 53" src="https://user-images.githubusercontent.com/110044546/181257833-d522d61b-d4b5-4a2e-bc64-dc974bfd0305.png">

**Comment by minjeong930610** [comment]
넵
