### ISSUE TITLE
input 눌렀을때 확대되는 효과 없애기

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#105]
## 💁 설명

- 프로필 편집 input 눌렀을때 확대됩니다.

## 🎬 시나리오
1. 모바일에서 접속 - 프로필 소개 편집
2. 인풋 터치시 확대됨
3. 인풋 입력 완료해도 화면이 계속 확대됨

## 📢 예상 결과
- 확대되지 않기

## 🃏 실제 결과 
- 확대됨

## 📌 스크린샷
![IMG_3269](https://user-images.githubusercontent.com/110044546/181446475-76bca1c2-5597-4981-bee1-63884a870374.PNG)
![IMG_3270](https://user-images.githubusercontent.com/110044546/181446518-83a7b0f7-f027-42a9-8dd4-b4b71668f224.PNG)

**Comment by KangSoYeon** [comment]
` <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />`
mximum-scale=1 추가

**Comment by minjeong930610** [comment]
user-scalable 메타 추가하겠습니다 (유저 단말 확대 기능 허용 여부)
