### ISSUE TITLE
아이콘 svg 교체

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#106]
## 💁 설명

- 아직 안 바뀐 아이콘들이 있습니다. 채팅화면과 나의책방에서ㅠㅠ

## 🎬 시나리오
1. 
2.
3.

## 📢 예상 결과
- 

## 🃏 실제 결과 
- 

## 📌 스크린샷
- 
![IMG_3284 2](https://user-images.githubusercontent.com/110044546/181451733-2f496f04-c233-4808-a0de-441124819a3c.jpg)

![IMG_3285 2](https://user-images.githubusercontent.com/110044546/181451749-1161646c-4c43-444a-873e-0fce712fd002.jpg)

**Comment by minjeong930610** [comment]
우선 제가 눈에 보이는 작업된 페이지 먼저 교체하고 배포한거여서요 지금 올려주신 작업 페이지들은 아직 진행 중인 페이지라서 작업하면서 교체될 예정입니다^^
