### ISSUE TITLE
로그인 화면에서 '이용약관' 및 '개인정보처리방침' 텍스트 버튼 선택 시 홈 화면으로 이동하는 이슈

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#111]
## 💁 설명

로그인 화면에서 '이용약관' 및 '개인정보처리방침' 텍스트 버튼 선택 시 홈 화면으로 이동하는 이슈

## 🎬 시나리오
1. 로그인 화면에서 '이용약관' 및 '개인정보처리방침' 텍스트 버튼 선택 시
2.
3.

## 📢 예상 결과
'이용약관' 버튼 선택 시, 브라우저를 호출하며 https://www.notion.so/bside/f180c697e98b4b40bf1c69b13590120f 로 링크 이동
'개인정보처리방침' 버튼 선택 시, 브라우저를 호출하며 https://www.notion.so/bside/d8e5b8f0a54c4328b3e2bceb5be2d8d7 로 링크 이동

## 🃏 실제 결과 
'이용약관' 및 '개인정보처리방침' 텍스트 버튼 선택 시 홈 화면으로 이동

## 📌 스크린샷
![Screenshot_20220803004050](https://user-images.githubusercontent.com/110044464/182417401-555955cc-c91f-4617-a06a-ae70255b4731.jpg)

**Comment by minjeong930610** [comment]
상훈님 이거 설정 페이지 내 작업해서 페이지 이동으로 처리했습니다.
