### ISSUE TITLE
로그인 화면에서 GNB가 비노출되도록 수정

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#112]
## 💁 설명

- 로그인 화면에서 GNB가 비노출되도록 수정

## 🎬 시나리오
1. 로그인 화면 진입
2.
3.

## 📢 예상 결과
- 로그인 화면에서 GNB 영역 비노출

## 🃏 실제 결과 
- 로그인 화면에서 GNB 영역 노출

## 📌 스크린샷
![Screenshot_20220803004050](https://user-images.githubusercontent.com/110044464/182418106-f53d0524-29c5-4842-a6d9-504d3b61cac1.jpg)

**Comment by minjeong930610** [comment]
수정됐습니다.
