### ISSUE TITLE
책의 썸네일이 보이지 않는 이슈 

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#113]
## 💁 설명

- 몇몇 포스트의 책의 썸네일이 보이지 않는 이슈

## 🎬 시나리오
1. 소격동으로 위치 이동
2. 홈 화면에서 도서 포스트 확인
3.

## 📢 예상 결과
- 등록한 책의 썸네일이 정상적으로 노출

## 🃏 실제 결과 
-책의 썸네일이 보이지 않음

## 📌 스크린샷
![Screenshot_20220803005333](https://user-images.githubusercontent.com/110044464/182418810-7cabdc3f-1f5f-4747-ab87-2d1697e56260.jpg)
![Screenshot_20220803005348](https://user-images.githubusercontent.com/110044464/182418918-cf471f8e-7e49-41be-b02f-69abe2b95e1b.jpg)

**Comment by minjeong930610** [comment]
디폴트 이미지 적용했고 배포하면 확인 가능하실거에요!
