### ISSUE TITLE
책 제목 없이 등록된 책 포스트가 존재하는 이슈

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#114]
## 💁 설명
책 제목 없이 등록된 책 포스트가 존재하는 이슈

## 🎬 시나리오
1. 소격동으로 위치 이동
2.
3.

## 📢 예상 결과
- 책 제목이 노출

## 🃏 실제 결과 
- 책 제목이 없는 도서 포스트 존재

## 📌 스크린샷
![Screenshot_20220803005605](https://user-images.githubusercontent.com/110044464/182419249-a8e739ea-1c46-48ae-9e0b-b764ecbeb399.jpg)

**Comment by KangSoYeon** [comment]
예전 테스트 데이터라 이제는 제목이 없을 시 데이터가 들어가지 않으므로 close 하겠습니다.
