### ISSUE TITLE
홈 화면 헤더에 검색, 찜, 알림 버튼 비노출되도록 수정 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#122]
## 💁 설명

- 홈 화면 헤더에 검색, 찜, 알림 버튼 비노출되도록 수정 건

## 🎬 시나리오
1. 홈 화면으로 이동
2.
3.

## 📢 예상 결과
- 홈 화면 헤더에 검색, 찜, 알림 버튼 비노출 -> MVP 스펙 아웃하기로 한 기능입니다.

## 🃏 실제 결과 
- 홈 화면 헤더에 검색, 찜, 알림 버튼 노출

## 📌 스크린샷
![Screenshot_20220804222723](https://user-images.githubusercontent.com/110044464/182858825-0b46d768-17a0-4bf1-8b8b-59aa86766165.jpg)

**Comment by minjeong930610** [comment]
넵 수정하겠습니다.
