### ISSUE TITLE
네이버 불완전 로그인 시, 로그인이 되는 이슈

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#123]
## 💁 설명

네이버 불완전 로그인 시, 나의 책방 화면이 빈화면으로 노출되는 이슈

## 🎬 시나리오
1. 비로그인 상태에서 로그인 화면으로 이동
2. 네이버 로그인 선택
3. 프로필 확인 화면으로 이동
4. Back 버튼 사용 

## 📢 예상 결과
1. 비로그인 상태에서 로그인 화면으로 이동
2. 네이버 로그인 선택
3. 프로필 확인 화면으로 이동
4. Back 버튼 사용 시, 비로그인 상태로 홈 화면으로 이동

## 🃏 실제 결과 
1. 비로그인 상태에서 로그인 화면으로 이동
2. 네이버 로그인 선택
3. 프로필 확인 화면으로 이동
4. Back 버튼 사용 시, 홈 화면으로 이동
5. 대여관리 화면, 채팅 화면의 이용이 가능하나, 나의 책방 화면 이동 시 빈화면으로 노출

## 📌 스크린샷
나의 책방 이동 시 빈화면
![Screenshot_20220804223017](https://user-images.githubusercontent.com/110044464/182860060-6450c18c-23cb-4351-bef2-3abff46b5d52.jpg)

비로그인 상태여야 하나, 대여관리 화면이 보임
![Screenshot_20220804223415](https://user-images.githubusercontent.com/110044464/182860141-885d33c0-5ede-4dcb-b364-3d9c29c1e99d.jpg)

**Comment by minjeong930610** [comment]
넵 회원가입 프로필 화면에서 회원가입 진행하지 않고 백버튼 클릭 시 이슈 확인했습니다.
