### ISSUE TITLE
도서 검색 시, 검색용 키패드로 노출되도록 수정 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#124]
## 💁 설명
도서 검색 시, 검색용 키패드로 노출되도록 수정 건

## 🎬 시나리오
1. 홈 화면으로 이동
2. + 플러스 버튼으로 도서 대여 글쓰기 화면으로 이동
3. 도서 검색 버튼 선택
4. 검색 input box 선택 시

## 📢 예상 결과
- 검색용 키패드로 노출

## 🃏 실제 결과 
- 일반 키패드로 노출

## 📌 스크린샷
이슈 화면
![Screenshot_20220804-224209_Samsung Internet](https://user-images.githubusercontent.com/110044464/182863255-4c1fb855-1ff9-4720-854e-440394161554.jpg)

[참조] 검색용 키패드
![Screenshot_20220804-224235_Samsung Internet](https://user-images.githubusercontent.com/110044464/182863338-cfa47e47-88a0-4f3d-9a4e-97f6b6fd30b6.jpg)

**Comment by KangSoYeon** [comment]
호오 이런게 있는 줄 몰랐군요!
input type 넣으면 해결 될것 같아서 일단 넣어봤습니다 
재발생하면 reopen 하겠습니다.
ed5f54535452fada03344e98fcfbb65b577a5b5c

**Comment by 77sanghoon** [comment]
@KangSoYeon 
AOS에서 이슈 재현됩니다~
삼성인터넷 브라우저
갤럭시 노트 10 5G 기종에서 확인했습니다.

혹시 MR만 넣고 배포는 안되서 운영환경에서 확인이 안된 것인지 궁금합니다~

**Comment by KangSoYeon** [comment]
@77sanghoon  상훈님~ 배포 방금 해서 이제 반영됐습니다~
확인 부탁드립니다!
