### ISSUE TITLE
도서 여러 건 검색 시, 검색 결과가 바뀌지 않는 이슈 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#125]
## 💁 설명

- 도서 여러 건 검색 시, 검색 결과가 바뀌지 않는 이슈 건

## 🎬 시나리오
1. 홈 화면으로 이동
2. + 플러스 버튼으로 도서 대여 글쓰기 화면으로 이동
3. 도서 검색 버튼 선택
4. 여러 검색어 검색

## 📢 예상 결과
- '하이' 검색 시, '하이'에 대한 검색결과만 노출
- '유아' 검색 시, '유아'에 대한 검색결과만 노출
- '진리' 검색 시, '진리'에 대한 검색결과만 노출

## 🃏 실제 결과 
- '하이' 검색 시, '하이'에 대한 검색결과만 노출
- '유아', '진리' 검색 시, '하이'에 대한 검색결과가 그대로 노출 && 검색 결과 개수는 바뀜

## 📌 스크린샷

https://user-images.githubusercontent.com/110044464/182865552-d28a6a4d-cfec-4e8e-9aaa-1204647c49e5.mp4

**Comment by KangSoYeon** [comment]
확인

**Comment by KangSoYeon** [comment]
민정님이 infinite scroll 추가하면서 수정 해주셨네요 ㅎㅎ
