### ISSUE TITLE
책 설명 및 느낀점 텍스트 영역을 입력한 텍스트 줄 수에 맞게 늘이는 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#128]
## 💁 설명

- 책 설명 및 느낀점 텍스트 영역을 입력한 텍스트 줄 수에 맞게 늘이는 건

## 🎬 시나리오
1. 홈 화면으로 이동
2. + 플러스 버튼으로 도서 대여 글쓰기 화면으로 이동
3. 도서 대여 글쓰기 화면으로 이동
4. 책 설명 및 느낀점 텍스트 영역에 텍스트 입력 시

## 📢 예상 결과
- 텍스트 영역이 있어서 줄바꿈 되면서 텍스트 입력
- 텍스트 줄 수에 맞게 텍스트 영역 세로길이 늘어남

## 🃏 실제 결과 
- 한줄로 쭉 이어지며, 텍스트 영역이 고정됨

## 📌 스크린샷
![Screenshot_20220804231532](https://user-images.githubusercontent.com/110044464/182870913-a8f43e54-b1bd-4a43-8c97-d92cfa42abf7.jpg)

**Comment by minjeong930610** [comment]
소연님 수정 페이지에 적용되어 있어요 따와서 수정해주세요

**Comment by KangSoYeon** [comment]
넵! 수정 페이지 보고 수정했습니다!
https://github.com/ttukttak3/ttukttak/pull/160/commits/df619748e71044d396ba8231d4527e2064fe69ad
