### ISSUE TITLE
내 포스트 보기 화면 진입시 채팅목록으로 연결

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#140]
## 💁 설명

- 내가 등록한 도서 포스트 화면에서 하단 버튼이 채팅하기 -> 채팅목록으로 바뀌어야 함.

## 🎬 시나리오
1. 내가 등록한 도서 클릭
2. 포스트 화면에서 버튼 확인
3. 

## 📢 예상 결과
-  채팅목록 버튼이 있고 클릭시 채팅목록으로 이동

## 🃏 실제 결과 
-  채팅하기로 되어있고, 동작을 안함

## 📌 스크린샷
<img width="403" alt="스크린샷 2022-08-05 오후 6 34 04" src="https://user-images.githubusercontent.com/110044546/183049171-5a23deca-5235-4f3c-9c24-c903bdc9385c.png">

**Comment by KangSoYeon** [comment]
수정 완료
https://github.com/ttukttak3/ttukttak/pull/160/commits/1aeafc4fe31565e06b435a1d35d5ced4b97f1836
