### ISSUE TITLE
채팅 도서 정보 영역 고정

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#142]
## 💁 설명

- 채팅 화면에서 스크롤 해도 움직이지 않게 도서 정보 영역을 고정해야 함

## 🎬 시나리오
1. 채팅을 함
2. 채팅이 길어질수록 정보 영역이 사라지는 걸 확인
3.

## 📢 예상 결과
- 계속 정보 볼 수 있게

## 🃏 실제 결과 
- 올라가서 가려짐

## 📌 스크린샷
![IMG_E02B1950D6EA-1](https://user-images.githubusercontent.com/110044546/183053804-d009ea4a-eb3f-422a-b13e-83e2cedf9a03.jpeg)

**Comment by minjeong930610** [comment]
확인
