### ISSUE TITLE
디자인 시안에 "대여자"로만 명칭 기입됨

### ISSUE THREAD

**Issue by hyojeongyii** [ttukttak3/ttukttak#146]
## 💁 설명

- 대여관리 > 빌려준 내역(=대여내역) > 대여 현황 상세 페이지(ST1.3) & 대여 내역 페이지(ST1.4)
- 내가 대여자 (빌려준 사람)이므로, 상대는 "차입자"로 명칭되어야합니다. (ex. 차입자와의 채팅, 차입자 프로필)

## 개선 사항
1. AS-IS : 대여자와의 채팅 TO-BE : 차입자와의 채팅
2. AS-IS : 대여자와 프로필 TO-BE : 차입자 프로필

## 📌 스크린샷
- 가능하다면 오류메세지나 동작결과에 대해 스크린샷을 첨부해주세요
- 
<img width="390" alt="ST1 3_대여현황 상세 복사본" src="https://user-images.githubusercontent.com/48341076/183065067-2587a9c9-da9d-4ff7-8986-c368d9fbb1e6.png">

**Comment by KangSoYeon** [comment]
넵! 수정하겠습니다!

**Comment by makingbird** [comment]
네!! 디자인에서도 수정했습니다!

**Comment by KangSoYeon** [comment]
디자인, 개발 반영 완료
