### ISSUE TITLE
네이버 로그인 시 프로필 이미지 못가져오는 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#147]
## 💁 설명

- 네이버 로그인 시 프로필 이미지 못가져오는 건

## 🎬 시나리오
1. 네이버 로그인 진행
2.
3.

## 📢 예상 결과
- 네이버로부터 프로필 이미지 가져옴

## 🃏 실제 결과 
- 프로필 이미지를 못 가져옴

## 📌 스크린샷
![Screenshot_20220805-203248_Samsung Internet.jpg](https://user-images.githubusercontent.com/110044464/183069269-139fb61f-daf6-44ea-8e60-7e2c13ac7fa1.jpg)

**Comment by minjeong930610** [comment]
확인

**Comment by KangSoYeon** [comment]
민정님 댓글대신 assignees 바꿔주시면 될것 같아요!
