### ISSUE TITLE
포스트보기 인디케이터 색 변경

### ISSUE THREAD

**Issue by makingbird** [ttukttak3/ttukttak#149]
## 💁 설명

- 이미지가 2개 이상일 경우 회색으로 나오는데, 눈에 띄지 않아서 색 변경을 요청합니당!
- #333 -> #5F6368(Black 4_line)

## 🎬 시나리오
1.
2.
3.

## 📢 예상 결과
- 인디케이터를 보고 이미지가 여러 개 있구나 하고 넘겨 볼 것

## 🃏 실제 결과 
- 색이 눈에 띄지 않아 지나침

## 📌 스크린샷
<img width="466" alt="스크린샷 2022-08-07 오전 12 04 32" src="https://user-images.githubusercontent.com/110044546/183254850-44ec899d-20f7-49da-b193-46d904e5101b.png">

**Comment by minjeong930610** [comment]
넵
