### ISSUE TITLE
서비스이용약관 화면에서 개인정보처리방침 하이퍼링크 선택 시, 헤더 영역 미변경 이슈 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#153]
## 💁 설명
- 서비스이용약관 화면에서 개인정보처리방침 하이퍼링크 선택 시, 헤더 영역 미변경 이슈 건

## 🎬 시나리오
1. 서비스이용약관 화면으로 이동
2. 화면 내 '개인정보처리방침' 하이퍼링크 선택
3.

## 📢 예상 결과
- 헤더영역이 '개인 정보 처리 방침'으로 수정

## 🃏 실제 결과 
- 헤더영역 미변경

## 📌 스크린샷
https://user-images.githubusercontent.com/110044464/185432404-1ebae342-25d3-4830-b95b-fd4c2a52f906.mp4

**Comment by minjeong930610** [comment]
확인
