### ISSUE TITLE
로그인 화면에서 첫번째 물리적 Back 버튼 미작동 이슈 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#154]
## 💁 설명
- 로그인 화면에서 첫번째 물리적 Back 버튼 미작동 이슈 건

## 🎬 시나리오
1. 로그인 화면으로 이동
2. 물리적 Back버튼 사용
3.

## 📢 예상 결과
- 물리적 Back 버튼 정상 작동

## 🃏 실제 결과 
- 첫번째 물리적 Back 버튼 사용 시, 미작동
- 두번째 물리적 Back 버튼 사용 시, 작동

## 📌 스크린샷
https://user-images.githubusercontent.com/110044464/185433397-02311026-e1db-4c4d-84df-587699d007bd.mp4

**Comment by minjeong930610** [comment]
확인
