### ISSUE TITLE
카카오톡 로그인 주의사항 추가된 로그인 화면으로 수정 건 

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#155]
## 💁 설명
- 카카오톡 로그인 주의사항 추가된 로그인 화면으로 수정 건 

## 🎬 시나리오
1. 로그인 화면
2.
3.

## 📢 예상 결과
- 카카오톡 로그인 주의사항이 추가된 로그인 화면으로 수정(스크린샷에 첨부)

## 🃏 실제 결과 
- 이전 로그인 화면이 유지

## 📌 스크린샷
![image](https://user-images.githubusercontent.com/110044464/185434320-cc2e9252-07e3-410c-af13-6335998e1f9b.png)

**Comment by minjeong930610** [comment]
확인
