### ISSUE TITLE
로그인 화면 > 닉네임 미입력 시 validation 미작동 건

### ISSUE THREAD

**Issue by 77sanghoon** [ttukttak3/ttukttak#156]
## 💁 설명
- 로그인 화면 > 닉네임 미입력 시 validation 미작동 건

## 🎬 시나리오
1. 로그인 화면으로 이동
2. 닉네임 미입력 후 회원가입 완료 버튼 선택 시

## 📢 예상 결과
- '닉네임 입력이 필요합니다.' 에러메시지 노출

## 🃏 실제 결과 
- 닉네임 없이 회원가입 완료

## 📌 스크린샷
https://user-images.githubusercontent.com/110044464/185435709-cc34992a-2a71-4b3a-926e-019acb53facc.mp4

**Comment by minjeong930610** [comment]
확인
