### ISSUE TITLE
채팅메시지 입력 후 Enter를 눌렀을 때 아무 동작도 하지 않음

### ISSUE THREAD

**Issue by Songwonseok** [ttukttak3/ttukttak#96]
## 💁 설명

- 채팅방에서 채팅메시지 입력 후 `Enter`키를 눌렀을 때 메시지가 보내지지 않습니다.

## 🎬 시나리오
1. 채팅 탭에서 채팅방 입장
2. 메시지 입력창에 메시지 입력
3. Enter키 누름

## 📢 예상 결과
- 메시지 입력버튼 눌렀을 때와 같이 메시지가 보내져야함

## 🃏 실제 결과 
- 메시지가 보내지지 않음

## 📌 스크린샷
<img width="315" alt="image" src="https://user-images.githubusercontent.com/7006837/181016547-9a4d7717-9a8d-4cec-8ecf-735fdb12c472.png">

**Comment by KangSoYeon** [comment]
수정완료
