### ISSUE TITLE
첫 로그인 후 나의 책방 접근 시 흰색 화면으로 뜸

### ISSUE THREAD

**Issue by gisu11** [ttukttak3/ttukttak#99]
## 💁 설명

- 이슈설명을 적어주세요

## 🎬 시나리오
1. 첫 로그인 시도 후 완료
2. 나의 책방 접근 시 흰색 화면 (서비스 내장 뒤로가기로도 화면이 변하지 않음)
3.캐시 지운 후 다시 시도 시 접속 가능

## 📢 예상 결과
- 로그인 완료 후 나의 책방 접근 시 정상적으로 화면이 보여짐

## 🃏 실제 결과 
- 흰 화면만 보여지고 무조건 화면을 종료하고 캐시를 지워야만 함

## 📌 스크린샷
- 가능하다면 오류메세지나 동작결과에 대해 스크린샷을 첨부해주세요

**Comment by minjeong930610** [comment]
첫 로그인 시 location 이슈로 수정했습니다.
